import random
from contextlib import asynccontextmanager

import httpx
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

# ─── Knowledge base (loaded on startup) ───────────────────────────────────────
# This simulates a vector database / document store used in RAG.
PRODUCTS: list[dict] = []


@asynccontextmanager
async def lifespan(app: FastAPI):
    """FastAPI lifespan event — runs on startup and shutdown."""
    global PRODUCTS
    print("🚀 Starting up: loading knowledge base from DummyJSON...")
    async with httpx.AsyncClient() as client:
        response = await client.get(
            "https://dummyjson.com/products?limit=100"
            "&select=id,title,description,category,price,stock,brand,rating,thumbnail"
        )
        data = response.json()
        PRODUCTS = data["products"]
    print(f"✅ Knowledge base loaded: {len(PRODUCTS)} products indexed.")
    yield
    print("🛑 Shutting down.")


app = FastAPI(
    title="Toy RAG + Function Calling API",
    description=(
        "A learning system demonstrating FastAPI, RAG (Retrieval-Augmented Generation), "
        "and function calling / tool use — without a real LLM API key."
    ),
    version="1.0.0",
    lifespan=lifespan,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Replace with your frontend URL in production
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ─── Mock AI: pre-defined response templates ──────────────────────────────────
# In a real system, these would be generated by an LLM using the retrieved
# context as a prompt prefix. Here we use fixed templates to simulate the pattern.

AI_THINKING_TEMPLATES = [
    "The user provided index {id}. I need to call the `get_product` tool to fetch "
    "the relevant document before I can generate a grounded response.",
    "Input detected: numeric index {id}. Executing retrieval step first — "
    "calling `get_product(id={id})` to pull context from the knowledge base.",
    "Planning: (1) call get_product to retrieve the document at index {id}, "
    "(2) use the returned data as context for my answer.",
    "Tool call required. The user wants product #{id}. "
    "I cannot answer without grounding — fetching document now.",
]

AI_RESPONSE_PREFIXES = [
    "Based on the retrieved context, here is what I found:",
    "After searching the knowledge base, I located the following record:",
    "The retrieval step returned a high-confidence match. Grounded answer:",
    "Tool call completed. Here is the document-grounded response:",
    "Using the retrieved document as context, my answer is:",
    "The semantic search returned one result. Based on that context:",
]


# ─── Tool / Function definition ───────────────────────────────────────────────
# This is the "tool" the AI would call in a real function-calling setup.
# In OpenAI / Anthropic APIs, you'd define this as a JSON schema and the model
# decides when to call it. Here we call it deterministically for learning.

TOOL_DEFINITION = {
    "name": "get_product",
    "description": "Retrieve a product record from the company knowledge base by its index.",
    "parameters": {
        "type": "object",
        "properties": {
            "id": {
                "type": "integer",
                "description": "Zero-based index of the product to retrieve (0–99).",
            }
        },
        "required": ["id"],
    },
}


def get_product(product_id: int) -> dict:
    """
    The actual tool implementation.

    In real function calling:
      1. The LLM sees the tool definition (above) and decides to call it.
      2. Your backend executes this function with the LLM's chosen args.
      3. The result is sent back to the LLM as context for its final answer.
    """
    if not PRODUCTS:
        return {"error": "Knowledge base not loaded yet. Try again in a moment."}
    if product_id < 0 or product_id >= len(PRODUCTS):
        return {
            "error": (
                f"Index {product_id} is out of range. Code Crushed..."
                f"Valid range: 0 to {len(PRODUCTS) - 1}. Code Crushed..."
            )
        }
    return PRODUCTS[product_id]


# ─── Pydantic models ──────────────────────────────────────────────────────────
# Pydantic validates request/response shapes — this is FastAPI's superpower.
# Every field is type-checked at runtime. No more silent type bugs.

class ChatRequest(BaseModel):
    message: str


class ToolCall(BaseModel):
    tool_definition: dict
    args: dict
    result: dict


class ChatResponse(BaseModel):
    user_message: str
    step_1_ai_thinking: str
    step_2_tool_call: ToolCall
    step_3_rag_context: str
    step_4_ai_response: str
    knowledge_base_size: int
    error: bool = False


# ─── Routes ───────────────────────────────────────────────────────────────────

@app.get("/chat-api/")
async def health():
    """Health check — also shows knowledge base status."""
    return {
        "status": "ok",
        "knowledge_base_size": len(PRODUCTS),
        "message": "Toy RAG + Function Calling API is running. No worries.",
    }


@app.get("/chat-api/products")
async def list_products(limit: int = 10, offset: int = 0):
    """
    Browse the loaded knowledge base.
    Try: GET /chat-api/products?limit=5&offset=0
    """
    subset = PRODUCTS[offset : offset + limit]
    return {
        "total": len(PRODUCTS),
        "offset": offset,
        "limit": limit,
        "products": subset,
    }


@app.get("/chat-api/products/{product_id}")
async def get_product_by_id(product_id: int):
    """
    Direct product lookup — same logic as the tool, exposed as a REST endpoint.
    This is useful for exploring the data manually.
    """
    result = get_product(product_id)
    if "error" in result:
        from fastapi import HTTPException
        raise HTTPException(status_code=404, detail=result["error"])
    return result


@app.get("/chat-api/tool-definition")
async def tool_definition():
    """
    Returns the tool/function schema as an AI API would define it.
    In OpenAI format this goes into the `tools` array of your chat request.
    """
    return TOOL_DEFINITION


@app.post("/chat-api/chat", response_model=ChatResponse)
async def chat(req: ChatRequest):
    """
    The main chat endpoint. Demonstrates the full RAG + function-calling pipeline:

    1. AI THINKING  — the model decides it needs to call a tool
    2. TOOL CALL    — your backend executes get_product(id=N)
    3. RAG CONTEXT  — the retrieved document is injected as context
    4. AI RESPONSE  — a response grounded in the retrieved document
    """
    message = req.message.strip()

    # ── Parse the number ──────────────────────────────────────────────────────
    try:
        product_id = int(message)
    except ValueError:
        return ChatResponse(
            user_message=message,
            step_1_ai_thinking=(
                f'Oh, man. The user typed "{message}" which is not a valid integer. '
                "I cannot call get_product without a numeric index."
            ),
            step_2_tool_call=ToolCall(
                tool_definition=TOOL_DEFINITION,
                args={"id": message},
                result={"error": "Input must be a whole number."},
            ),
            step_3_rag_context="No documents retrieved — the query was not a valid index.",
            step_4_ai_response=(
                f'"{message}" is not a number. '
                "I beg you to type a number between 0-99 so that I can look up to the company database."
            ),
            knowledge_base_size=len(PRODUCTS),
            error=True,
        )

    # ── Step 1: AI thinking (what a real LLM would output before a tool call) ─
    thinking = random.choice(AI_THINKING_TEMPLATES).format(id=product_id)

    # ── Step 2: Execute the tool call ─────────────────────────────────────────
    tool_result = get_product(product_id)

    # ── Step 3 + 4: RAG context and grounded response ─────────────────────────
    if "error" in tool_result:
        rag_context = (
            f"Retrieval failed. Reason: {tool_result['error']} "
            "No context injected into the prompt."
        )
        ai_response = (
            f"I tried to look up index {product_id}, but: {tool_result['error']} "
            f"Try a number between 0 and {len(PRODUCTS) - 1}."
        )
        error = True
    else:
        p = tool_result
        rag_context = (
            f"Retrieved 1 document from knowledge base (index {product_id}). "
            f"Document: '{p.get('title')}' in category '{p.get('category')}'. "
            "Injecting into prompt context for grounded generation."
        )
        prefix = random.choice(AI_RESPONSE_PREFIXES)
        ai_response = (
            f"{prefix}\n\n"
            f"**{p.get('title', 'Unknown')}** — by {p.get('brand', 'Unknown brand')}\n"
            f"Category: {p.get('category', 'N/A')}  |  "
            f"Price: ${p.get('price', 'N/A')}  |  "
            f"Rating: {p.get('rating', 'N/A')}/5  |  "
            f"Stock: {p.get('stock', 'N/A')} units\n\n"
            f"{p.get('description', 'No description available.')}"
        )
        error = False

    return ChatResponse(
        user_message=message,
        step_1_ai_thinking=thinking,
        step_2_tool_call=ToolCall(
            tool_definition=TOOL_DEFINITION,
            args={"id": product_id},
            result=tool_result,
        ),
        step_3_rag_context=rag_context,
        step_4_ai_response=ai_response,
        knowledge_base_size=len(PRODUCTS),
        error=error,
    )
